# safelist
branches:
  only:
      - /.*/

matrix:
  fast_finish: true
  include:
      - os: linux
        dist: xenial
        sudo: required

language: java
jdk:
  - openjdk8

script: |

  curl -LO https://raw.githubusercontent.com/FISCO-BCOS/FISCO-BCOS/master/tools/build_chain.sh && chmod u+x build_chain.sh
  bash <(curl -s https://raw.githubusercontent.com/FISCO-BCOS/FISCO-BCOS/master/tools/ci/download_bin.sh) -b dev
  echo "127.0.0.1:4 agency1 1,2,3" > ipconf
  ./build_chain.sh -e bin/fisco-bcos -f ipconf -p 30300,20200,8545
  ./nodes/127.0.0.1/start_all.sh
  ./nodes/127.0.0.1/fisco-bcos -v
  cp nodes/127.0.0.1/sdk/* src/main/resources/
  ./gradlew clean verGJF
  ./gradlew clean build	
  ./gradlew clean test
